name: Actualizar EPG diariamente

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a medianoche (UTC)
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Generar EPG
        run: python generar_epg.py

      - name: Commit y push de los cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add guiaiptv.xml
          git commit -m "Actualización automática del EPG"
          git push
